Repository swe-e4/pgv, pull requests merged in 2019-11, with the labels that each got.

#6 Migrations and models
  app/Appointment.php
  app/Group.php
  app/Http/Controllers/AppointmentController.php
  app/Http/Controllers/GroupController.php
  app/Http/Controllers/MilestoneController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/StudentController.php
  app/Milestone.php
  app/Role.php
  app/Student.php
  app/User.php
  database/factories/AppointmentFactory.php
  database/factories/GroupFactory.php
  database/factories/StudentFactory.php
  database/factories/UserFactory.php
  database/migrations/2019_11_13_211326_create_roles_table.php
  database/migrations/2019_11_13_300000_create_users_table.php
  database/migrations/2019_11_13_310000_create_milestones_table.php
  database/migrations/2019_11_13_320000_create_groups_table.php
  database/migrations/2019_11_13_330000_create_appointments_table.php
  database/migrations/2019_11_13_340000_create_students_table.php
  database/migrations/2019_11_14_300000_create_group_milestone_table.php
  database/seeds/AppointmentsSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/GroupSeeder.php
  database/seeds/MilestoneSeeder.php
  database/seeds/RoleSeeder.php
  database/seeds/StudentSeeder.php
  database/seeds/UserSeeder.php
Labels: enhancement

#7 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#8 feat(CONTRIBUTING.md): add contribution guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement

#9 feat(LICENSE): add license
  LICENSE
Labels: documentation, enhancement

#10 feat: update contribution guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement

#11 feat: user login
  database/factories/UserFactory.php
  database/migrations/2019_11_13_300000_create_users_table.php
Labels: enhancement

#15 feat: implement student api
  app/Http/Controllers/StudentController.php
  routes/api.php
Labels: enhancement

#12 feat: implement group api
  app/Http/Controllers/GroupController.php
  routes/api.php
Labels: enhancement

#24 feat: implement appointment api
  app/Http/Controllers/AppointmentController.php
  routes/api.php
Labels: enhancement

#25 feat: implement milestone api
  app/Http/Controllers/MilestoneController.php
  routes/api.php
Labels: enhancement

#26 fix: naming of api route and controller
  routes/api.php
Labels: bug

#27 feat: improve group controller
  app/Http/Controllers/GroupController.php
Labels: enhancement

#28 feat: improve api
  app/Http/Controllers/Auth/RegisterController.php
  config/auth.php
  database/factories/UserFactory.php
  database/migrations/2019_11_13_300000_create_users_table.php
  routes/api.php
Labels: enhancement
